//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerId_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustomerId_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OfficialId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OfficialIdType" type="{http://www.BrightWare.com.sa/SADADWare}OfficialIdType_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerId_Type", propOrder = {
    "officialId",
    "officialIdType"
})
public class CustomerIdType {

    @XmlElement(name = "OfficialId")
    private String officialId;
    @XmlElement(name = "OfficialIdType")
    @XmlSchemaType(name = "string")
    private OfficialIdTypeType officialIdType;

    /**
     * Gets the value of the officialId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOfficialId() {
        return officialId;
    }

    /**
     * Sets the value of the officialId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOfficialId(String value) {
        this.officialId = value;
    }

    /**
     * Gets the value of the officialIdType property.
     *
     * @return
     *     possible object is
     *     {@link OfficialIdTypeType }
     *
     */
    public OfficialIdTypeType getOfficialIdType() {
        return officialIdType;
    }

    /**
     * Sets the value of the officialIdType property.
     *
     * @param value
     *     allowed object is
     *     {@link OfficialIdTypeType }
     *
     */
    public void setOfficialIdType(OfficialIdTypeType value) {
        this.officialIdType = value;
    }

}
