//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 03:37:06 PM AST 
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sa.tamkeentech.tbs.schemas.refund package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RefundRq_QNAME = new QName("http://www.BrightWare.com.sa/SADADWare", "RefundRq");
    private final static QName _RefundRs_QNAME = new QName("http://www.BrightWare.com.sa/SADADWare", "RefundRs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sa.tamkeentech.tbs.schemas.refund
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RefundRqType }
     * 
     */
    public RefundRqType createRefundRqType() {
        return new RefundRqType();
    }

    /**
     * Create an instance of {@link RefundRsType }
     * 
     */
    public RefundRsType createRefundRsType() {
        return new RefundRsType();
    }

    /**
     * Create an instance of {@link RefundRecType }
     * 
     */
    public RefundRecType createRefundRecType() {
        return new RefundRecType();
    }

    /**
     * Create an instance of {@link CustomerIdType }
     * 
     */
    public CustomerIdType createCustomerIdType() {
        return new CustomerIdType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link RefundNotifyRqType }
     * 
     */
    public RefundNotifyRqType createRefundNotifyRqType() {
        return new RefundNotifyRqType();
    }

    /**
     * Create an instance of {@link RefundNotificationRecType }
     * 
     */
    public RefundNotificationRecType createRefundNotificationRecType() {
        return new RefundNotificationRecType();
    }

    /**
     * Create an instance of {@link RefundNotifyRsType }
     * 
     */
    public RefundNotifyRsType createRefundNotifyRsType() {
        return new RefundNotifyRsType();
    }

    /**
     * Create an instance of {@link RefundReconRqType }
     * 
     */
    public RefundReconRqType createRefundReconRqType() {
        return new RefundReconRqType();
    }

    /**
     * Create an instance of {@link RefundReconRecType }
     * 
     */
    public RefundReconRecType createRefundReconRecType() {
        return new RefundReconRecType();
    }

    /**
     * Create an instance of {@link RefundReconRsType }
     * 
     */
    public RefundReconRsType createRefundReconRsType() {
        return new RefundReconRsType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundRqType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RefundRqType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.BrightWare.com.sa/SADADWare", name = "RefundRq")
    public JAXBElement<RefundRqType> createRefundRq(RefundRqType value) {
        return new JAXBElement<RefundRqType>(_RefundRq_QNAME, RefundRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundRsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RefundRsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.BrightWare.com.sa/SADADWare", name = "RefundRs")
    public JAXBElement<RefundRsType> createRefundRs(RefundRsType value) {
        return new JAXBElement<RefundRsType>(_RefundRs_QNAME, RefundRsType.class, null, value);
    }

}
