//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 03:37:06 PM AST 
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfficialIdType_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfficialIdType_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NAT"/&gt;
 *     &lt;enumeration value="IQA"/&gt;
 *     &lt;enumeration value="PAS"/&gt;
 *     &lt;enumeration value="BIS"/&gt;
 *     &lt;enumeration value="ACT"/&gt;
 *     &lt;enumeration value="SID"/&gt;
 *     &lt;enumeration value="BTL"/&gt;
 *     &lt;enumeration value="BED"/&gt;
 *     &lt;enumeration value="BIE"/&gt;
 *     &lt;enumeration value="SED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OfficialIdType_Type")
@XmlEnum
public enum OfficialIdTypeType {

    NAT,
    IQA,
    PAS,
    BIS,
    ACT,
    SID,
    BTL,
    BED,
    BIE,
    SED;

    public String value() {
        return name();
    }

    public static OfficialIdTypeType fromValue(String v) {
        return valueOf(v);
    }

}
