//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.BrightWare.com.sa/SADADWare",
    /*xmlns = {@XmlNs(prefix = "", namespaceURI = "http://www.BrightWare.com.sa/SADADWare")},*/
    elementFormDefault = XmlNsForm.QUALIFIED)
package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
