//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 03:37:06 PM AST 
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundStatus_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RefundStatus_Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Accepted"/&gt;
 *     &lt;enumeration value="Already_Reconciled"/&gt;
 *     &lt;enumeration value="Duplicate"/&gt;
 *     &lt;enumeration value="Mismatch"/&gt;
 *     &lt;enumeration value="Not_In_Bank"/&gt;
 *     &lt;enumeration value="Not_In_Sadad"/&gt;
 *     &lt;enumeration value="Pending"/&gt;
 *     &lt;enumeration value="Processed"/&gt;
 *     &lt;enumeration value="Processing_Failed"/&gt;
 *     &lt;enumeration value="Reconciled"/&gt;
 *     &lt;enumeration value="Timeout"/&gt;
 *     &lt;enumeration value="UnReconciled"/&gt;
 *     &lt;enumeration value="Rejected"/&gt;
 *     &lt;enumeration value="Expired"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RefundStatus_Type")
@XmlEnum
public enum RefundStatusType {

    @XmlEnumValue("Accepted")
    ACCEPTED("Accepted"),
    @XmlEnumValue("Already_Reconciled")
    ALREADY_RECONCILED("Already_Reconciled"),
    @XmlEnumValue("Duplicate")
    DUPLICATE("Duplicate"),
    @XmlEnumValue("Mismatch")
    MISMATCH("Mismatch"),
    @XmlEnumValue("Not_In_Bank")
    NOT_IN_BANK("Not_In_Bank"),
    @XmlEnumValue("Not_In_Sadad")
    NOT_IN_SADAD("Not_In_Sadad"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("Processed")
    PROCESSED("Processed"),
    @XmlEnumValue("Processing_Failed")
    PROCESSING_FAILED("Processing_Failed"),
    @XmlEnumValue("Reconciled")
    RECONCILED("Reconciled"),
    @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"),
    @XmlEnumValue("UnReconciled")
    UN_RECONCILED("UnReconciled"),
    @XmlEnumValue("Rejected")
    REJECTED("Rejected"),
    @XmlEnumValue("Expired")
    EXPIRED("Expired");
    private final String value;

    RefundStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RefundStatusType fromValue(String v) {
        for (RefundStatusType c: RefundStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
