//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundReconRq_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RefundReconRq_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrcDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RefundedAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ReconAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="UnReconAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TransFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="RefundReconRec" type="{http://www.BrightWare.com.sa/SADADWare}RefundReconRec_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundReconRq_Type", propOrder = {
    "rqUID",
    "prcDt",
    "refundedAmt",
    "reconAmt",
    "unReconAmt",
    "transFees",
    "refundReconRec"
})
public class RefundReconRqType {

    @XmlElement(name = "RqUID")
    private String rqUID;
    @XmlElement(name = "PrcDt")
    private String prcDt;
    @XmlElement(name = "RefundedAmt", required = true)
    private BigDecimal refundedAmt;
    @XmlElement(name = "ReconAmt", required = true)
    private BigDecimal reconAmt;
    @XmlElement(name = "UnReconAmt", required = true)
    private BigDecimal unReconAmt;
    @XmlElement(name = "TransFees", required = true)
    private BigDecimal transFees;
    @XmlElement(name = "RefundReconRec")
    private List<RefundReconRecType> refundReconRec;

    /**
     * Gets the value of the rqUID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the prcDt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrcDt() {
        return prcDt;
    }

    /**
     * Sets the value of the prcDt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrcDt(String value) {
        this.prcDt = value;
    }

    /**
     * Gets the value of the refundedAmt property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getRefundedAmt() {
        return refundedAmt;
    }

    /**
     * Sets the value of the refundedAmt property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setRefundedAmt(BigDecimal value) {
        this.refundedAmt = value;
    }

    /**
     * Gets the value of the reconAmt property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getReconAmt() {
        return reconAmt;
    }

    /**
     * Sets the value of the reconAmt property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setReconAmt(BigDecimal value) {
        this.reconAmt = value;
    }

    /**
     * Gets the value of the unReconAmt property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getUnReconAmt() {
        return unReconAmt;
    }

    /**
     * Sets the value of the unReconAmt property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setUnReconAmt(BigDecimal value) {
        this.unReconAmt = value;
    }

    /**
     * Gets the value of the transFees property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getTransFees() {
        return transFees;
    }

    /**
     * Sets the value of the transFees property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setTransFees(BigDecimal value) {
        this.transFees = value;
    }

    /**
     * Gets the value of the refundReconRec property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refundReconRec property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefundReconRec().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefundReconRecType }
     *
     *
     */
    public List<RefundReconRecType> getRefundReconRec() {
        if (refundReconRec == null) {
            refundReconRec = new ArrayList<RefundReconRecType>();
        }
        return this.refundReconRec;
    }

}
