//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundRec_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RefundRec_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CustomerId" type="{http://www.BrightWare.com.sa/SADADWare}CustomerId_Type" minOccurs="0"/&gt;
 *         &lt;element name="RefundId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RefundType" type="{http://www.BrightWare.com.sa/SADADWare}RefundType" minOccurs="0"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ExpDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankAcct" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PmtId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundRec_Type", propOrder = {
    "customerId",
    "refundId",
    "refundType",
    "amount",
    "expDt",
    "bankAcct",
    "mobileNumber",
    "pmtId"
})
public class RefundRecType {

    @XmlElement(name = "CustomerId")
    private CustomerIdType customerId;
    @XmlElement(name = "RefundId")
    private String refundId;
    @XmlElement(name = "RefundType")
    @XmlSchemaType(name = "string")
    private RefundType refundType;
    @XmlElement(name = "Amount", required = true)
    private BigDecimal amount;
    @XmlElement(name = "ExpDt")
    private String expDt;
    @XmlElement(name = "BankAcct")
    private Long bankAcct;
    @XmlElement(name = "MobileNumber")
    private String mobileNumber;
    @XmlElement(name = "PmtId")
    private String pmtId;

    /**
     * Gets the value of the customerId property.
     *
     * @return
     *     possible object is
     *     {@link CustomerIdType }
     *
     */
    public CustomerIdType getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     *
     * @param value
     *     allowed object is
     *     {@link CustomerIdType }
     *
     */
    public void setCustomerId(CustomerIdType value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the refundId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * Sets the value of the refundId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRefundId(String value) {
        this.refundId = value;
    }

    /**
     * Gets the value of the refundType property.
     *
     * @return
     *     possible object is
     *     {@link RefundType }
     *
     */
    public RefundType getRefundType() {
        return refundType;
    }

    /**
     * Sets the value of the refundType property.
     *
     * @param value
     *     allowed object is
     *     {@link RefundType }
     *
     */
    public void setRefundType(RefundType value) {
        this.refundType = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the expDt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExpDt() {
        return expDt;
    }

    /**
     * Sets the value of the expDt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExpDt(String value) {
        this.expDt = value;
    }

    /**
     * Gets the value of the bankAcct property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getBankAcct() {
        return bankAcct;
    }

    /**
     * Sets the value of the bankAcct property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setBankAcct(Long value) {
        this.bankAcct = value;
    }

    /**
     * Gets the value of the mobileNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * Sets the value of the mobileNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMobileNumber(String value) {
        this.mobileNumber = value;
    }

    /**
     * Gets the value of the pmtId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPmtId() {
        return pmtId;
    }

    /**
     * Sets the value of the pmtId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPmtId(String value) {
        this.pmtId = value;
    }

}
