//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for RefundRq_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RefundRq_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RqUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RefundRec" type="{http://www.BrightWare.com.sa/SADADWare}RefundRec_Type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundRq_Type", propOrder = {
    "rqUID",
    "timestamp",
    "refundRec"
})
@XmlRootElement(name = "RefundRq" /*namespace = "http://www.BrightWare.com.sa/SADADWare"*/)
public class RefundRqType {

    @XmlElement(name = "RqUID")
    private String rqUID;
    @XmlElement(name = "Timestamp")
    private String timestamp;
    @XmlElement(name = "RefundRec")
    private RefundRecType refundRec;

    /**
     * Gets the value of the rqUID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the refundRec property.
     *
     * @return
     *     possible object is
     *     {@link RefundRecType }
     *
     */
    public RefundRecType getRefundRec() {
        return refundRec;
    }

    /**
     * Sets the value of the refundRec property.
     *
     * @param value
     *     allowed object is
     *     {@link RefundRecType }
     *
     */
    public void setRefundRec(RefundRecType value) {
        this.refundRec = value;
    }

}
