//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundNotificationRec_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RefundNotificationRec_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SadadRefundTransNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankRefundTransNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerId" type="{http://www.BrightWare.com.sa/SADADWare}CustomerId_Type" minOccurs="0"/&gt;
 *         &lt;element name="RefundId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="DueDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RefundType" type="{http://www.BrightWare.com.sa/SADADWare}RefundType"/&gt;
 *         &lt;element name="RefundStatus" type="{http://www.BrightWare.com.sa/SADADWare}RefundStatus_Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundNotificationRec_Type", propOrder = {
    "sadadRefundTransNum",
    "bankRefundTransNum",
    "customerId",
    "refundId",
    "bankId",
    "amount",
    "dueDt",
    "effDt",
    "refundType",
    "refundStatus"
})
public class RefundNotificationRecType {

    @XmlElement(name = "SadadRefundTransNum")
    private String sadadRefundTransNum;
    @XmlElement(name = "BankRefundTransNum")
    private String bankRefundTransNum;
    @XmlElement(name = "CustomerId")
    private CustomerIdType customerId;
    @XmlElement(name = "RefundId")
    private String refundId;
    @XmlElement(name = "BankId")
    private String bankId;
    @XmlElement(name = "Amount", required = true)
    private BigDecimal amount;
    @XmlElement(name = "DueDt")
    private String dueDt;
    @XmlElement(name = "EffDt")
    private String effDt;
    @XmlElement(name = "RefundType", required = true)
    @XmlSchemaType(name = "string")
    private RefundType refundType;
    @XmlElement(name = "RefundStatus", required = true)
    @XmlSchemaType(name = "string")
    private RefundStatusType refundStatus;

    /**
     * Gets the value of the sadadRefundTransNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSadadRefundTransNum() {
        return sadadRefundTransNum;
    }

    /**
     * Sets the value of the sadadRefundTransNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSadadRefundTransNum(String value) {
        this.sadadRefundTransNum = value;
    }

    /**
     * Gets the value of the bankRefundTransNum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBankRefundTransNum() {
        return bankRefundTransNum;
    }

    /**
     * Sets the value of the bankRefundTransNum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBankRefundTransNum(String value) {
        this.bankRefundTransNum = value;
    }

    /**
     * Gets the value of the customerId property.
     *
     * @return
     *     possible object is
     *     {@link CustomerIdType }
     *
     */
    public CustomerIdType getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     *
     * @param value
     *     allowed object is
     *     {@link CustomerIdType }
     *
     */
    public void setCustomerId(CustomerIdType value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the refundId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * Sets the value of the refundId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRefundId(String value) {
        this.refundId = value;
    }

    /**
     * Gets the value of the bankId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * Sets the value of the bankId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBankId(String value) {
        this.bankId = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the dueDt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDueDt() {
        return dueDt;
    }

    /**
     * Sets the value of the dueDt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDueDt(String value) {
        this.dueDt = value;
    }

    /**
     * Gets the value of the effDt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEffDt() {
        return effDt;
    }

    /**
     * Sets the value of the effDt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEffDt(String value) {
        this.effDt = value;
    }

    /**
     * Gets the value of the refundType property.
     *
     * @return
     *     possible object is
     *     {@link RefundType }
     *
     */
    public RefundType getRefundType() {
        return refundType;
    }

    /**
     * Sets the value of the refundType property.
     *
     * @param value
     *     allowed object is
     *     {@link RefundType }
     *
     */
    public void setRefundType(RefundType value) {
        this.refundType = value;
    }

    /**
     * Gets the value of the refundStatus property.
     *
     * @return
     *     possible object is
     *     {@link RefundStatusType }
     *
     */
    public RefundStatusType getRefundStatus() {
        return refundStatus;
    }

    /**
     * Sets the value of the refundStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link RefundStatusType }
     *
     */
    public void setRefundStatus(RefundStatusType value) {
        this.refundStatus = value;
    }

}
