//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.03 at 03:37:06 PM AST
//


package sa.tamkeentech.tbs.schemas.refund;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Signature_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Signature_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="XPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SignatureValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Signature_Type", propOrder = {
    "xPath",
    "signatureValue"
})
public class SignatureType {

    @XmlElement(name = "XPath")
    private String xPath;
    @XmlElement(name = "SignatureValue")
    private String signatureValue;

    /**
     * Gets the value of the xPath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXPath() {
        return xPath;
    }

    /**
     * Sets the value of the xPath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXPath(String value) {
        this.xPath = value;
    }

    /**
     * Gets the value of the signatureValue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSignatureValue() {
        return signatureValue;
    }

    /**
     * Sets the value of the signatureValue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSignatureValue(String value) {
        this.signatureValue = value;
    }

}
